module.exports = {
  block: {display: 'block'},
  inlineBlock: {display: 'inline-block'},
  inlineFlex: {display: 'inline-flex'},
  grid: {display: 'grid'},
  inlineGrid: {display: 'inline-grid'},
  inline: {display: 'inline'},
  hidden: {display: 'none'},
  contents: {display: 'contents'},
  table: {display: 'table'},
  tableCaption: {display: 'table-caption'},
  tableCell: {display: 'table-cell'},
  tableColumn: {display: 'table-column'},
  tableColumnGroup: {display: 'table-column-group'},
  tableHeaderGroup: {display: 'table-header-group'},
  tableFooterGroup: {display: 'table-footer-group'},
  tableRowGroup: {display: 'table-row-group'},
  tableRow: {display: 'table-row'},
  listItem: {display: 'list-item'},

  invisible: {visibility: 'hidden'},
  visible: {visibility: 'visible'},

  boxBorder: {boxSizing: 'border-box'},
  boxContent: {boxSizing: 'content-box'},

  floatRight: {float: 'right'},
  floatLeft: {float: 'left'},
  floatNone: {float: 'none'},

  clearLeft: {clear: 'left'},
  clearRight: {clear: 'right'},
  clearBoth: {clear: 'both'},
  clearNone: {clear: 'none'},

  overflowVisible: {overflow: 'visible'},
  overflowHidden: {overflow: 'hidden'},
  overflowClip: {overflow: 'clip'},
  overflowScroll: {overflow: 'scroll'},
  overflowAuto: {overflow: 'auto'},
  overflowXVisible: {overflowX: 'visible'},
  overflowXHidden: {overflowX: 'hidden'},
  overflowXClip: {overflowX: 'clip'},
  overflowXScroll: {overflowX: 'scroll'},
  overflowXAuto: {overflowX: 'auto'},
  overflowYVisible: {overflowY: 'visible'},
  overflowYHidden: {overflowY: 'hidden'},
  overflowYClip: {overflowY: 'clip'},
  overflowYScroll: {overflowY: 'scroll'},
  overflowYAuto: {overflowY: 'auto'},

  static: {position: 'static'},
  fixed: {position: 'fixed'},
  absolute: {position: 'absolute'},
  relative: {position: 'relative'},
  sticky: {position: 'sticky'},
  top: {top: '0'},
  right: {right: '0'},
  left: {left: '0'},
  bottom: {bottom: '0'},

  z: {
    auto: {zIndex: 'auto'},
    0: {zIndex: 0},
    1: {zIndex: 10},
    2: {zIndex: 20},
    3: {zIndex: 30},
    4: {zIndex: 40},
    5: {zIndex: 50},
    10: {zIndex: 100},
  },

  shadow: {
    boxShadow: '0px 1px 4px 0px rgba(0,0,0,0.11), 0px 1px 2px -1px rgba(0,0,0,0.11)',
    sm: {boxShadow: '0px 1px 2px 0px rgba(0,0,0,0.11)'},
    md: {boxShadow: '0px 5px 8px -1px rgba(0,0,0,0.11), 0px 2px 4px -2px rgba(0,0,0,0.11)'},
    lg: {boxShadow: '0px 8px 14px -3px rgba(0,0,0,0.11), 0px 4px 6px -4px rgba(0,0,0,0.11)'},
    xl: {boxShadow: '0px 16px 24px -5px rgba(0,0,0,0.11), 0px 8px 10px -6px rgba(0,0,0,0.11)'}
  }
};
