module.exports = {
  classes: [
    'active',
    'link',
    'any-link',
    'autofill',
    'checked',
    'default',
    'disabled',
    'empty',
    'enabled',
    'first-child',
    'first-of-type',
    'focus',
    'focus-visible',
    'focus-within',
    'hover',
    'indeterminate',
    'in-range',
    'invalid',
    'last-child',
    'last-of-type',
    {even: 'nth-child(even)'},
    {odd: 'nth-child(odd)'},
    'only-child',
    'only-of-type',
    'out-of-range',
    'placeholder-shown',
    'read-only',
    'required',
    'valid',
    'visited',
    'target'
  ],
  elements: [
    'after',
    'before',
    'first-letter',
    'first-line',
    'file-selector-button',
    'selection',
    'placeholder',
    'marker'
  ]
};
